-- AlterTable
ALTER TABLE "projections" ADD COLUMN     "def_fum_rec" DECIMAL(5,2),
ADD COLUMN     "def_int" DECIMAL(5,2),
ADD COLUMN     "def_pa_allow" DECIMAL(5,2),
ADD COLUMN     "def_sack" DECIMAL(5,2),
ADD COLUMN     "def_safety" DECIMAL(5,2),
ADD COLUMN     "def_td" DECIMAL(5,2),
ADD COLUMN     "fg_made" DECIMAL(5,2),
ADD COLUMN     "fg_miss" DECIMAL(5,2),
ADD COLUMN     "fum_lost" DECIMAL(5,2),
ADD COLUMN     "pass_2pt" DECIMAL(5,2),
ADD COLUMN     "pass_int" DECIMAL(5,2),
ADD COLUMN     "pass_td" DECIMAL(5,2),
ADD COLUMN     "pass_yd" DECIMAL(6,2),
ADD COLUMN     "rec" DECIMAL(5,2),
ADD COLUMN     "rec_2pt" DECIMAL(5,2),
ADD COLUMN     "rec_td" DECIMAL(5,2),
ADD COLUMN     "rec_yd" DECIMAL(6,2),
ADD COLUMN     "rush_2pt" DECIMAL(5,2),
ADD COLUMN     "rush_td" DECIMAL(5,2),
ADD COLUMN     "rush_yd" DECIMAL(6,2),
ADD COLUMN     "xp_made" DECIMAL(5,2);
